# Generated by Django 4.0.4 on 2022-05-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('AP', 'Applied'), ('AC', 'Accepted'), ('RJ', 'Rejected')], default='AP', max_length=2)),
            ],
        ),
    ]
