# Generated by Django 4.0.4 on 2022-05-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_alter_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default='sdf@saf.ds', max_length=254),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Applied', max_length=10),
        ),
    ]
